name: Validate Infrastructure

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  terraform:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:

      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - run: terraform init -backend=false

      - run: terraform validate

  kubernetes:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: azure/setup-kubectl@v4

      - name: Validate manifests
        run: |
          kubectl apply --dry-run=client \
          -f apps/nginx/